#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.


# Our workflow consists of three steps:

#### for CIFAR100: ####

# 1.step - storing layer representations:
# e.g. for wrn_40_2 teacher model which has 18 potential hint positions(sub-blocks):
export TEACHER_MODEL='wrn_40_2'
export TEACHER_PATH='./save/models/wrn_40_2_cifar100/wrn_40_2_75.61.pth'
export NUM_LAYERS=18

for i in {1..18}
do
	python -u store_hints.py --g $i --model_t $TEACHER_MODEL --t_path $TEACHER_PATH "$@"
done

# 2.step - clustering these representations:
export METRIC_NAME='r2'
export NUM_CLUSTERS=3

python -u k_means.py --hints_dir /results/wrn_40_2_75.61.pth --num_clusters $NUM_CLUSTERS --num_layers $NUM_LAYERS --metric_name $METRIC_NAME "$@"
# we take the center points of clusters as hint positions.


# 3.step - distillation using proposed hint positions:
export CENTROIDS_FILE='/results/'${TEACHER_MODEL}'_'${NUM_CLUSTERS}'kmeans_mean_'${METRIC_NAME}'_centroids.txt'
while read line; do echo $line; done < $CENTROIDS_FILE
export HINT_POSITIONS=$line
echo $HINT_POSITIONS # e.g. "7,29,49" # determined in previous step


python -u train_student.py --path_t $TEACHER_PATH --distill attention --model_s wrn_16_2 -r 1 -a 1.5 -b 1 --trial 0 --hint_points $HINT_POSITIONS --epochs 240


#### for ImageNet: ####

# # 1.step - storing layer representations:
# python -u store_hints_imagenet.py --t_path './save/models/ResNet34_imagenet/ResNet34_333f7ec4.pth' --data_folder '/data/fake_imagenet/' "$@"

# # 2.step - clustering these representations:
# # we use 4 hint positions for imagenet experiments:
# export METRIC_NAME='r2'
# export NUM_CLUSTERS=4
# export NUM_LAYERS=16

# python -u k_means.py --hints_dir '/results/ResNet34_333f7ec4' --num_clusters $NUM_CLUSTERS --num_layers $NUM_LAYERS --metric_name $METRIC_NAME "$@"

# # 3.step - distillation using proposed hint positions:
# export TEACHER_MODEL='ResNet34'
# export CENTROIDS_FILE='/results/'${TEACHER_MODEL}'_'${NUM_CLUSTERS}'kmeans_mean_'${METRIC_NAME}'_centroids.txt'
# while read line; do echo $line; done < $CENTROIDS_FILE
# export HINT_POSITIONS=$line
# echo $HINT_POSITIONS # e.g. "2,6,11,15" # determined in previous step

# python -m torch.distributed.launch --master_port 9200 --nproc_per_node=1 train_stu_imagenet.py --dali_cpu --alpha 0.5 --beta 0.01 --gamma 1 --lr 0.1 --distillation --hint_type attention   --hint_points $HINT_POSITIONS '/path/to/imagenet'


